/* DUTA LED - Admin UI v3 */
(function(){
'use strict';
const URL='https://opgeeqnucxrdqcgwcuge.supabase.co';
const KEY='sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA';
const db=window.supabase?.createClient(URL,KEY);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function inject(){const tabs=document.querySelector('.tabs');if(!tabs)return;if(!$('tabPromo')){const b=document.createElement('button');b.id='tabPromo';b.className='btn tab';b.type='button';b.textContent='🖼️ Promo Header';tabs.appendChild(b)}if(!$('tabSaran')){const b=document.createElement('button');b.id='tabSaran';b.className='btn tab';b.type='button';b.textContent='💬 Saran & Kritik';tabs.appendChild(b)}if(!$('saranView')){const s=document.createElement('section');s.id='saranView';s.className='hidden';s.innerHTML='<div class="saran-box"><h2>💬 Saran & Kritik</h2><div id="saranList"><div class="empty">Memuat...</div></div></div>';document.querySelector('main.wrap')?.appendChild(s)}hidePersonal();setupTabs();patchStyles();patchClicks();loadSaran()}
function hidePersonal(){['tabPersonalFinance','personalFinanceView'].forEach(id=>$(id)?.remove());document.querySelectorAll('.tabs button').forEach(b=>{if(/keuangan pribadi/i.test(b.textContent||''))b.remove()})}
function views(){return{orders:$('ordersView'),products:$('productsView'),promo:$('promoAdminPanel'),saran:$('saranView'),store:$('storeFinanceView')}}
function show(name){const v=views();Object.keys(v).forEach(k=>v[k]?.classList.toggle('hidden',k!==name));document.querySelectorAll('.tabs .tab').forEach(b=>b.classList.remove('active'));const id={orders:'tabOrders',products:'tabProducts',promo:'tabPromo',saran:'tabSaran',store:'tabStoreFinance'}[name];$(id)?.classList.add('active');if(name==='saran')loadSaran()}
function setupTabs(){if(setupTabs.done)return;setupTabs.done=1;const map={tabOrders:'orders',tabProducts:'products',tabPromo:'promo',tabSaran:'saran',tabStoreFinance:'store'};Object.entries(map).forEach(([id,name])=>$(id)?.addEventListener('click',()=>show(name)));show('orders')}
async function loadSaran(){const box=$('saranList');if(!box||!db)return;const {data,error}=await db.from('saran_masukan').select('*').order('created_at',{ascending:false});if(error){box.innerHTML='<div class="empty">Gagal memuat saran.</div>';return}box.innerHTML=data?.length?data.map(x=>`<article class="saran-item"><div><b>${esc(x.email||'Tanpa email')}</b><small>${new Date(x.created_at).toLocaleString('id-ID')}</small></div><p>${esc(x.pesan||'')}</p></article>`).join(''):'<div class="empty">Belum ada saran atau kritik.</div>'}
function statusClass(s){return 'st-'+String(s||'BARU').toLowerCase().replace(/\s+/g,'-')}
function patchStyles(){if($('adminUiV3Style'))return;const s=document.createElement('style');s.id='adminUiV3Style';s.textContent='.tabs{flex-wrap:wrap}.saran-box{background:#fff;border:1px solid #e1e6ed;border-radius:16px;padding:16px}.saran-box h2{margin:0 0 14px}.saran-item{border:1px solid #edf0f4;border-radius:12px;padding:12px;margin-bottom:9px}.saran-item b,.saran-item small{display:block}.saran-item small{font-size:11px;color:#788395;margin-top:3px}.saran-item p{margin:9px 0 0;white-space:pre-wrap}.status.st-baru,.st-baru{background:#fff3cd!important;color:#8a6200!important}.status.st-diproses,.st-diproses{background:#dbeafe!important;color:#1d4ed8!important}.status.st-dikirim,.st-dikirim{background:#ede9fe!important;color:#6d28d9!important}.status.st-selesai,.st-selesai{background:#dcfce7!important;color:#15803d!important}.status.st-batal,.st-batal{background:#fee2e2!important;color:#b91c1c!important}.status-card.st-baru{border-left:5px solid #d9a400}.status-card.st-diproses{border-left:5px solid #2563eb}.status-card.st-dikirim{border-left:5px solid #7c3aed}.status-card.st-selesai{border-left:5px solid #16a34a}.status-card.st-batal{border-left:5px solid #dc2626}.note-share-actions{display:flex;gap:8px;margin-top:10px}.note-share-actions button{flex:1}.note-size{display:flex;gap:7px;align-items:center;margin:10px 0;font-size:12px}.note-size select{padding:8px;border:1px solid #d8dee7;border-radius:8px}.note-card{background:#fff;color:#111;padding:14px;font-family:Arial,sans-serif;width:100%;max-width:420px;margin:auto}.note-card h2{text-align:center;margin:0 0 3px}.note-card .center{text-align:center}.note-card table{width:100%;border-collapse:collapse;margin-top:8px}.note-card td{padding:4px 0;vertical-align:top}.note-card td:last-child{text-align:right}.note-card hr{border:0;border-top:1px dashed #999;margin:9px 0}.note-total{font-weight:900;font-size:16px}';document.head.appendChild(s)}
async function getOrder(id){if(!db)return null;const r=await db.from('pesanan').select('*,detail_pesanan(*)').eq('id',id).maybeSingle();return r.data||null}
async function getOrderByNumber(orderId){if(!db)return null;const r=await db.from('pesanan').select('*,detail_pesanan(*)').eq('order_id',orderId).maybeSingle();return r.data||null}
function buildNote(o){const rows=(o.detail_pesanan||[]).map(d=>`<tr><td>${esc(d.nama_produk)}<br>${Number(d.qty)||0} × Rp${Number(d.harga_saat_beli||0).toLocaleString('id-ID')}</td><td>Rp${Number(d.subtotal||0).toLocaleString('id-ID')}</td></tr>`).join('');return `<div class="note-card" id="noteCard"><h2>DUTA LED</h2><div class="center">Toko LED & Elektronik</div><hr><b>No:</b> ${esc(o.order_id)}<br><b>Tgl:</b> ${new Date(o.created_at).toLocaleString('id-ID')}<br><b>Pembeli:</b> ${esc(o.nama_pembeli)}<br><b>HP:</b> ${esc(o.no_hp)}<hr><table>${rows}</table><hr><table><tr><td class="note-total">TOTAL</td><td class="note-total">Rp${Number(o.total_harga||0).toLocaleString('id-ID')}</td></tr></table><hr>Status: ${esc(o.status||'BARU')}<br>Pembayaran: ${esc(o.metode_pembayaran||'-')}<br>Pengiriman: ${esc(o.metode_pengiriman||'-')}<p class="center">Terima kasih</p></div>`}
function noteHtml(o,px){return `<html><head><meta charset="utf-8"><title>${esc(o.order_id)}</title><style>@page{margin:0}body{margin:0;background:#fff}.note-card{box-sizing:border-box;width:${px}px;padding:18px;font:14px Arial,sans-serif;color:#111}.note-card h2{text-align:center;margin:0 0 4px}.center{text-align:center}.note-card table{width:100%;border-collapse:collapse}.note-card td{padding:5px 0;vertical-align:top}.note-card td:last-child{text-align:right}.note-card hr{border:0;border-top:1px dashed #999;margin:10px 0}.note-total{font-weight:900;font-size:17px}</style></head><body>${buildNote(o)}<script>window.onload=()=>window.print()<\/script></body></html>`}
function printSized(o,size){const px={struk:300,a5:559,a4:794}[size]||300;const w=window.open('','_blank','width=900,height=900');if(!w)return;w.document.write(noteHtml(o,px));w.document.close()}
async function shareNote(o){if(!o)return;document.getElementById('noteShareModal')?.remove();const m=document.createElement('div');m.id='noteShareModal';m.className='overlay';m.innerHTML=`<div class="modal"><div class="modal-head"><h2>📷 Gambar Nota</h2><button class="close" id="closeNoteShare">×</button></div><div class="note-size"><span>Ukuran nota:</span><select id="noteSize"><option value="struk">Struk</option><option value="a5">A5</option><option value="a4">A4</option></select></div>${buildNote(o)}<div class="note-share-actions"><button class="btn light" id="notePrint">🖨️ Cetak</button><button class="btn primary" id="noteWA">📤 Bagikan ke WA</button></div></div>`;document.body.appendChild(m);$('closeNoteShare').onclick=()=>m.remove();$('notePrint').onclick=()=>printSized(o,$('noteSize').value);$('noteWA').onclick=()=>makeShare(o)}
async function makeShare(o){const card=$('noteCard'),btn=$('noteWA');if(!card||!btn)return;btn.disabled=true;btn.textContent='⏳ Membuat gambar...';try{if(!window.html2canvas){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';document.head.appendChild(s);await new Promise((res,rej)=>{s.onload=res;s.onerror=rej})}const canvas=await window.html2canvas(card,{backgroundColor:'#fff',scale:2,useCORS:true});const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const file=new File([blob],`${o.order_id||'nota'}.png`,{type:'image/png'});const text=`Nota ${o.order_id||''} DUTA LED\nTotal: Rp${Number(o.total_harga||0).toLocaleString('id-ID')}`;if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Nota DUTA LED',text,files:[file]})}else{window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank');alert('Browser ini tidak bisa mengirim gambar langsung. WhatsApp dibuka untuk memilih penerima.')}}catch(e){if(e.name!=='AbortError')alert('Gagal membagikan nota: '+e.message)}finally{btn.disabled=false;btn.textContent='📤 Bagikan ke WA'}}
function addWaButtons(){document.querySelectorAll('#orderList .order').forEach(card=>{if(card.querySelector('[data-wa-order]'))return;const print=card.querySelector('[data-print-order]');const id=print?.dataset.printOrder;if(!id)return;const b=document.createElement('button');b.className='btn primary';b.dataset.waOrder=id;b.textContent='📤 WA';print.parentElement?.appendChild(b);const st=card.querySelector('.status');if(st)st.classList.add(statusClass(st.textContent));card.classList.add('status-card',statusClass(st?.textContent))})}
function patchClicks(){document.addEventListener('click',async e=>{const b=e.target.closest('[data-wa-order]');if(b){e.preventDefault();e.stopImmediatePropagation();const o=await getOrder(b.dataset.waOrder);if(o)shareNote(o)}},true);document.addEventListener('click',async e=>{const b=e.target.closest('[data-print-order]');if(b){e.preventDefault();e.stopImmediatePropagation();const o=await getOrder(b.dataset.printOrder);if(o)shareNote(o)}},true);document.addEventListener('click',async e=>{if(e.target.closest('#printFromDetail')){e.preventDefault();e.stopImmediatePropagation();const first=$('orderDetail')?.querySelector('b');const o=first?await getOrderByNumber(first.textContent.trim()):null;if(o)shareNote(o)}},true)}
function observeOrders(){const box=$('orderList');if(!box)return;new MutationObserver(addWaButtons).observe(box,{childList:true});addWaButtons()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{inject();setTimeout(observeOrders,500)});else{inject();setTimeout(observeOrders,500)}
window.shareOrderNote=shareNote;window.printOrderNote=printSized;
})();