"use strict";
const SUPABASE_URL="https://opgeeqnucxrdqcgwcuge.supabase.co";
const SUPABASE_KEY="sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA";
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let products=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const num=v=>Number(String(v??"").replace(/[^\d.-]/g,""))||0;
const rupiah=v=>"Rp"+num(v).toLocaleString("id-ID");
const salePrice=(p,d)=>Math.max(0,Math.round(num(p)*(100-num(d))/100));
function msg(t,bad=false){const e=$("message");e.textContent=t;e.style.background=bad?"#b42318":"#182230";e.classList.remove("hidden");clearTimeout(msg.t);msg.t=setTimeout(()=>e.classList.add("hidden"),3000)}
function imageOf(p){return Array.isArray(p.foto_urls)&&p.foto_urls[0]?p.foto_urls[0]:""}
function render(){const q=($("adminSearch")?.value||"").toLowerCase();const a=products.filter(p=>!q||String(p.nama||"").toLowerCase().includes(q)||String(p.sku||"").toLowerCase().includes(q));$("productList").innerHTML=a.length?a.map(p=>{const price=num(p.harga_jual),d=num(p.diskon),sale=salePrice(price,d);return `<article class="card"><img class="photo" src="${esc(imageOf(p))}" onerror="this.style.opacity=.2"><div><div class="name">${esc(p.nama)}</div><div class="cat">${esc(p.sku||"Tanpa SKU")} · Stok ${num(p.stok)}</div><div class="prices"><span class="normal">${d?rupiah(price):""}</span><span class="sale">${rupiah(d?sale:price)}</span>${d?`<span class="disc">-${d}%</span>`:""}</div></div><button class="edit" data-id="${esc(p.id)}">✏️ Edit Produk</button></article>`}).join(""):"<div class=\"empty\">Belum ada produk.</div>";document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>openEditor(products.find(p=>String(p.id)===String(b.dataset.id))))}
async function load(){const {data,error}=await db.from("produk").select("*").order("created_at",{ascending:false});if(error)return msg("Gagal mengambil produk: "+error.message,true);products=data||[];render()}
function openEditor(p=null){const f=$("productForm");f.reset();$("editorTitle").textContent=p?"Edit Produk":"Tambah Produk";f.elements.id.value=p?.id??"";f.elements.nama.value=p?.nama??"";f.elements.kategoriId.value=p?.kategori_id??"";f.elements.sku.value=p?.sku??"";f.elements.hargaPokok.value=p?.harga_pokok??"";f.elements.hargaJual.value=p?.harga_jual??"";f.elements.diskon.value=p?.diskon??0;f.elements.stok.value=p?.stok??0;f.elements.berat.value=p?.berat??"";f.elements.deskripsi.value=p?.deskripsi??"";f.elements.fotoUrls.value=Array.isArray(p?.foto_urls)?p.foto_urls.join("\n"):"";f.elements.isActive.checked=p?.is_active!==false;updatePrice();$("editor").classList.remove("hidden")}
function closeEditor(){$("editor").classList.add("hidden")}
function updatePrice(){const f=$("productForm");$("autoDiscount").textContent=rupiah(salePrice(f.elements.hargaJual.value,f.elements.diskon.value))}
function dataForm(){const f=$("productForm");return{nama:f.elements.nama.value.trim(),kategori_id:f.elements.kategoriId.value.trim()||null,sku:f.elements.sku.value.trim()||null,harga_pokok:num(f.elements.hargaPokok.value)||null,harga_jual:num(f.elements.hargaJual.value),diskon:num(f.elements.diskon.value),stok:num(f.elements.stok.value),berat:num(f.elements.berat.value)||null,deskripsi:f.elements.deskripsi.value.trim()||null,foto_urls:f.elements.fotoUrls.value.split("\n").map(x=>x.trim()).filter(Boolean),is_active:f.elements.isActive.checked}}
async function saveProduct(){const f=$("productForm"),d=dataForm();if(!d.nama)return msg("Nama produk wajib diisi.",true);if(!d.harga_jual)return msg("Harga jual wajib diisi.",true);if(d.diskon<0||d.diskon>99)return msg("Diskon harus 0–99%.",true);const b=$("saveBtn");b.disabled=true;b.textContent="⏳ Menyimpan...";try{const id=f.elements.id.value.trim();let result;if(id){result=await db.from("produk").update(d).eq("id",id)}else{result=await db.from("produk").insert(d)}if(result.error)throw result.error;closeEditor();msg("Produk berhasil disimpan.");await load()}catch(e){msg("Gagal menyimpan: "+e.message,true)}finally{b.disabled=false;b.textContent="💾 Simpan Produk"}}
async function boot(){const {data,error}=await db.auth.getSession();if(error)return msg(error.message,true);if(data.session){$("login").classList.add("hidden");$("userEmail").textContent=data.session.user.email||"";await load()}else $("login").classList.remove("hidden")}
document.addEventListener("DOMContentLoaded",()=>{$("loginBtn").onclick=async()=>{const email=$("adminEmail").value.trim(),password=$("adminPassword").value;$("loginError").textContent="Masuk...";const {error}=await db.auth.signInWithPassword({email,password});if(error)$("loginError").textContent=error.message;else boot()};$("logoutBtn").onclick=async()=>{await db.auth.signOut();location.reload()};$("adminSearch").oninput=render;$("addProduct").onclick=()=>openEditor();$("closeEditor").onclick=closeEditor;$("cancel").onclick=closeEditor;$("productForm").onsubmit=e=>{e.preventDefault();saveProduct()};["hargaJual","diskon"].forEach(k=>$("productForm").elements[k].addEventListener("input",updatePrice));boot()});
