/* DUTA LED - Admin UI v4 */
(function(){
'use strict';
const URL='https://opgeeqnucxrdqcgwcuge.supabase.co',KEY='sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA';
const db=window.supabase?.createClient(URL,KEY),$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const cls=s=>'st-'+String(s||'BARU').toLowerCase().replace(/\s+/g,'-');
function removeFinance(){['tabPersonalFinance','personalFinanceView'].forEach(id=>$(id)?.remove());document.querySelectorAll('.tabs button,a').forEach(e=>{if(/^\s*keuangan pribadi\s*$/i.test(e.textContent||''))e.remove()})}
function style(){if($('adminV4Style'))return;const s=document.createElement('style');s.id='adminV4Style';s.textContent='.tabs{flex-wrap:wrap}.status-card.st-baru{border-left:5px solid #d9a400}.status-card.st-diproses{border-left:5px solid #2563eb}.status-card.st-dikirim{border-left:5px solid #7c3aed}.status-card.st-selesai{border-left:5px solid #16a34a}.status-card.st-batal{border-left:5px solid #dc2626}.status.st-baru{background:#fff3cd!important;color:#8a6200!important}.status.st-diproses{background:#dbeafe!important;color:#1d4ed8!important}.status.st-dikirim{background:#ede9fe!important;color:#6d28d9!important}.status.st-selesai{background:#dcfce7!important;color:#15803d!important}.status.st-batal{background:#fee2e2!important;color:#b91c1c!important}.admin-promo-tabpanel,.saran-box{background:#fff;border:1px solid #e4e8ee;border-radius:14px;padding:14px;margin-top:12px}.admin-promo-tabpanel h2,.saran-box h2{margin:0 0 12px}.promo-form{display:grid;gap:8px}.promo-form input{padding:10px;border:1px solid #ddd;border-radius:9px}.promo-form button{padding:10px;border:0;border-radius:9px;background:#e85f00;color:#fff;font-weight:800}.promo-list{margin-top:12px}.promo-row{display:grid;grid-template-columns:58px 1fr auto auto auto;gap:6px;align-items:center;padding:8px 0;border-bottom:1px solid #eee}.promo-row img{width:58px;height:42px;object-fit:contain;background:#f7f7f7;border-radius:6px}.promo-row small{display:block;color:#777;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.promo-row button{height:30px;border:1px solid #ddd;background:#fff;border-radius:7px}.saran-item{border:1px solid #edf0f4;border-radius:10px;padding:10px;margin:7px 0}.saran-item small{display:block;color:#777}.note-share-actions{display:flex;gap:8px;margin-top:10px}.note-share-actions button{flex:1}.note-size{display:flex;gap:7px;align-items:center;margin:10px 0}.note-size select{padding:8px;border:1px solid #ddd;border-radius:8px}.note-card{background:#fff;color:#111;padding:14px;font:13px Arial,sans-serif;max-width:420px;margin:auto}.note-card h2{text-align:center;margin:0 0 3px}.note-card .center{text-align:center}.note-card table{width:100%;border-collapse:collapse}.note-card td{padding:4px 0;vertical-align:top}.note-card td:last-child{text-align:right}.note-card hr{border:0;border-top:1px dashed #999;margin:9px 0}.note-total{font-size:16px;font-weight:900}@media(max-width:600px){.promo-row{grid-template-columns:48px 1fr auto auto}.promo-row img{width:48px;height:36px}.promo-row button[data-a="down"]{display:none}.note-share-actions{flex-direction:column}}
';document.head.appendChild(s)}
function panel(){if($('adminPromoPanel'))return;const p=document.createElement('section');p.id='adminPromoPanel';p.className='admin-promo-tabpanel hidden';p.innerHTML='<h2>🖼️ Promo Header</h2><form id="promoForm" class="promo-form"><input id="promoUrl" type="url" placeholder="Link gambar https://... (opsional jika upload)"><input id="promoFile" type="file" accept="image/*"><img id="promoPrev" hidden style="width:100%;max-height:150px;object-fit:contain;border-radius:9px;background:#f7f7f7"><input id="promoTitle" placeholder="Judul promo (opsional)"><input id="promoLink" type="url" placeholder="Link tujuan saat diklik (opsional)"><button>+ Tambah Promo</button></form><div id="promoList" class="promo-list">Memuat...</div><small>Upload maksimal 2 MB. File disimpan di Supabase Storage, bukan GitHub.</small>';document.querySelector('main.wrap')?.appendChild(p);bindPromo()}
function tabs(){const t=document.querySelector('.tabs');if(!t)return;const add=(id,text)=>{if($(id))return;const b=document.createElement('button');b.id=id;b.className='btn tab';b.type='button';b.textContent=text;t.appendChild(b);b.onclick=()=>show(id)};add('tabPromoV4','🖼️ Promo Header');add('tabSaranV4','💬 Saran & Kritik');$('tabPromoV4').onclick=()=>show('tabPromoV4');$('tabSaranV4').onclick=()=>show('tabSaranV4')}
function allViews(){return [...document.querySelectorAll('main.wrap > section,main.wrap > div')].filter(e=>!e.closest('#login'))}
function show(id){const promo=$('adminPromoPanel'),saran=$('saranViewV4');allViews().forEach(e=>{if(e===promo||e===saran||e.id==='ordersView'||e.id==='productsView')e.classList.add('hidden')});if(id==='tabPromoV4')promo?.classList.remove('hidden');else if(id==='tabSaranV4')saran?.classList.remove('hidden');else if(id==='tabOrders')$('ordersView')?.classList.remove('hidden');else if(id==='tabProducts')$('productsView')?.classList.remove('hidden');document.querySelectorAll('.tabs .tab').forEach(b=>b.classList.remove('active'));$(id)?.classList.add('active')}
function saran(){if($('saranViewV4'))return;const s=document.createElement('section');s.id='saranViewV4';s.className='hidden';s.innerHTML='<div class="saran-box"><h2>💬 Saran & Kritik</h2><div id="saranListV4">Memuat...</div></div>';document.querySelector('main.wrap')?.appendChild(s);loadSaran()}
async function loadSaran(){const b=$('saranListV4');if(!b||!db)return;const r=await db.from('saran_masukan').select('*').order('created_at',{ascending:false});b.innerHTML=r.error?'Gagal memuat saran.':r.data?.length?r.data.map(x=>`<div class="saran-item"><b>${esc(x.email||'Tanpa email')}</b><small>${new Date(x.created_at).toLocaleString('id-ID')}</small><div>${esc(x.pesan||'')}</div></div>`).join(''):'Belum ada saran atau kritik.'}
async function promos(){const b=$('promoList');if(!b||!db)return;const r=await db.from('promo').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(r.error){b.textContent='Gagal memuat promo.';return}b.innerHTML=r.data?.length?r.data.map((p,i)=>`<div class="promo-row"><img src="${esc(p.gambar_url)}"><div><b>${esc(p.judul||'Promo '+(i+1))}</b><small>${esc(p.link_url||'Tanpa link')}</small></div><button data-a="up" data-i="${i}">↑</button><button data-a="down" data-i="${i}">↓</button><button data-a="toggle" data-id="${p.id}">${p.is_active?'ON':'OFF'}</button><button data-a="del" data-id="${p.id}">×</button></div>`).join(''):'Belum ada promo.';b.querySelectorAll('button').forEach(x=>x.onclick=async()=>{const a=x.dataset.a;if(a==='del'){if(!confirm('Hapus promo ini?'))return;await db.from('promo').delete().eq('id',x.dataset.id)}else if(a==='toggle'){const row=r.data.find(p=>p.id===x.dataset.id);await db.from('promo').update({is_active:!row.is_active,updated_at:new Date().toISOString()}).eq('id',row.id)}else{const i=Number(x.dataset.i),j=a==='up'?i-1:i+1;if(!r.data[j])return;const a1=r.data[i],a2=r.data[j];await db.from('promo').update({sort_order:a2.sort_order+0.1}).eq('id',a1.id);await db.from('promo').update({sort_order:a1.sort_order+0.1}).eq('id',a2.id)}promos()})}
function bindPromo(){const f=$('promoForm');if(!f)return;const file=$('promoFile'),url=$('promoUrl'),prev=$('promoPrev');file.onchange=()=>{const x=file.files?.[0];if(!x)return;if(!x.type.startsWith('image/'))return alert('File harus gambar.');if(x.size>2*1024*1024)return alert('Maksimal 2 MB.');const rd=new FileReader();rd.onload=()=>{url.value='';prev.src=rd.result;prev.hidden=false};rd.readAsDataURL(x)};url.oninput=()=>{if(url.value){prev.src=url.value;prev.hidden=false}};f.onsubmit=async e=>{e.preventDefault();const x=file.files?.[0],u=url.value.trim();if(!x&&!u)return alert('Pilih gambar atau isi URL gambar.');const btn=f.querySelector('button');btn.disabled=true;btn.textContent='Menyimpan...';try{let image=u;if(x){const session=(await db.auth.getSession()).data.session;if(!session)throw Error('Sesi admin habis, silakan login lagi.');const fd=new FormData();fd.append('file',x);fd.append('title',$('promoTitle').value.trim());fd.append('link_url',$('promoLink').value.trim());const resp=await fetch(URL+'/functions/v1/promo-admin',{method:'POST',headers:{Authorization:'Bearer '+session.access_token},body:fd});const out=await resp.json();if(!resp.ok)throw Error(out.error||'Upload gagal');image=out.gambar_url||out.image_url||''}if(image){const r=await db.from('promo').insert({judul:$('promoTitle').value.trim()||null,gambar_url:image,link_url:$('promoLink').value.trim()||null,is_active:true,sort_order:Date.now()});if(r.error)throw r.error}f.reset();prev.hidden=true;await promos()}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent='+ Tambah Promo'}}}
function status(){document.querySelectorAll('#orderList .status').forEach(s=>s.classList.add(cls(s.textContent)));document.querySelectorAll('#orderList .order').forEach(c=>{const s=c.querySelector('.status');c.classList.add('status-card',cls(s?.textContent))})}
function init(){style();removeFinance();tabs();panel();saran();status();show('tabOrders');promos();setTimeout(removeFinance,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,300));else setTimeout(init,300);
})();