"use strict";
const API="https://script.google.com/macros/s/AKfycbyr4eSauu1RneZIrwwPVBilx21kWNrauE9V40D17dmrntqTu4U3OGi4fafAYHXcd-A/exec";
const KEY="dutaled_admin_key";
let products=[];
const $=id=>document.getElementById(id);
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function load(){try{const r=await fetch(API+"?action=produk&t="+Date.now(),{cache:"no-store"});const j=await r.json();products=Array.isArray(j.data)?j.data:[];render();}catch(e){msg("Gagal mengambil produk: "+e.message,true)}}
function render(){const q=($('adminSearch').value||'').toLowerCase();const list=products.filter(p=>String(p.nama||'').toLowerCase().includes(q));$('productList').innerHTML=list.length?list.map(p=>`<article class="product-row"><img src="${esc(p.gambar1||'image/no-image.png')}" onerror="this.src='image/no-image.png'"><div><h3>${esc(p.nama)}</h3><div class="meta">${esc(p.kategori||'Lainnya')} · Stok ${esc(p.stok??'-')}</div><div class="price">${rupiah(p.hargaDiskon||p.hargaJual)}</div></div><div class="actions"><button data-edit="${esc(p.id)}">✏️ Edit</button></div></article>`).join(''):'<div class="empty">Produk tidak ditemukan.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
function openEdit(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;fill(p);$('editorTitle').textContent='Edit Produk';$('editor').classList.remove('hidden')}
function fill(p={}){const f=$('productForm');['id','nama','kategori','hargaJual','hargaDiskon','diskon','stok','gambar1','gambar2','gambar3','deskripsi'].forEach(k=>{if(f.elements[k])f.elements[k].value=p[k]??''});preview()}
function openAdd(){fill({});$('editorTitle').textContent='Tambah Produk';$('editor').classList.remove('hidden')}
function close(){$('editor').classList.add('hidden')}
function preview(){['gambar1','gambar2','gambar3'].forEach(k=>{const box=document.querySelector(`[data-preview="${k}"]`),v=$('productForm').elements[k].value.trim();box.innerHTML=v?`<img src="${esc(v)}" onerror="this.style.display='none'">`:''})}
function msg(t,error=false){const m=$('message');m.textContent=t;m.classList.remove('hidden');m.style.background=error?'#fdecec':'';setTimeout(()=>m.classList.add('hidden'),4000)}
async function save(e){e.preventDefault();const f=e.currentTarget;const d=Object.fromEntries(new FormData(f).entries());d.action=d.id?'updateProduct':'createProduct';d.hargaJual=Number(d.hargaJual||0);d.hargaDiskon=Number(d.hargaDiskon||0);d.diskon=Number(d.diskon||0);d.stok=Number(d.stok||0);const key=prompt('Masukkan kunci admin untuk menyimpan:');if(!key)return;const btn=f.querySelector('.save');btn.disabled=true;btn.textContent='Menyimpan...';try{await fetch(API,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:d.action,key:key,data:d})});await new Promise(r=>setTimeout(r,1800));close();msg('Permintaan penyimpanan dikirim. Memuat ulang data...');await load();}catch(err){msg('Gagal mengirim data: '+err.message,true)}finally{btn.disabled=false;btn.textContent='Simpan Produk'}}
document.addEventListener('DOMContentLoaded',()=>{$('adminSearch').oninput=render;$('addProduct').onclick=openAdd;$('closeEditor').onclick=close;document.querySelector('.backdrop').onclick=close;$('productForm').addEventListener('submit',save);['gambar1','gambar2','gambar3'].forEach(k=>$('productForm').elements[k].addEventListener('input',preview));load();});
