"use strict";
const API="https://script.google.com/macros/s/AKfycbyr4eSauu1RneZIrwwPVBilx21kWNrauE9V40D17dmrntqTu4U3OGi4fafAYHXcd-A/exec";
let products=[];const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const disc=(c,j)=>{c=Number(c)||0;j=Number(j)||0;return c>0&&j>0&&j<c?Math.round((c-j)/c*100):0};
function row(p={}){let c=Number(p.hargaCoret??0)||0,j=Number(p.hargaDiskon??p.hargaJual??0)||0,d=disc(c,j);return `<tr data-id="${esc(p.id||"")}"><td><img class="thumb" src="${esc(p.gambar1||"")}" onerror="this.style.opacity=.25"></td><td><input data-k="nama" value="${esc(p.nama||"")}" placeholder="Nama produk"></td><td><input data-k="kategori" value="${esc(p.kategori||"")}" placeholder="Kategori"></td><td><input data-k="hargaCoret" type="number" min="0" value="${c||""}"></td><td><input data-k="hargaDiskon" type="number" min="0" value="${j||""}"></td><td><output class="discount">${d}%</output></td><td><input data-k="stok" type="number" min="0" value="${Number(p.stok)||0}"></td><td><input data-k="gambar1" type="url" value="${esc(p.gambar1||"")}" placeholder="URL gambar 1"></td><td><input data-k="gambar2" type="url" value="${esc(p.gambar2||"")}" placeholder="URL gambar 2"></td><td><input data-k="gambar3" type="url" value="${esc(p.gambar3||"")}" placeholder="URL gambar 3"></td><td><textarea data-k="deskripsi" rows="2" placeholder="Deskripsi">${esc(p.deskripsi||"")}</textarea></td></tr>`}
function render(){const q=($('adminSearch').value||'').toLowerCase();$('productBody').innerHTML=products.filter(p=>!q||String(p.nama||'').toLowerCase().includes(q)||String(p.kategori||'').toLowerCase().includes(q)).map(row).join('');bindRows()}
function bindRows(){document.querySelectorAll('#productBody tr').forEach(tr=>tr.querySelectorAll('input,textarea').forEach(el=>el.addEventListener('input',()=>{const c=tr.querySelector('[data-k="hargaCoret"]').value,j=tr.querySelector('[data-k="hargaDiskon"]').value;tr.querySelector('.discount').textContent=disc(c,j)+'%';if(el.dataset.k==='gambar1')tr.querySelector('.thumb').src=el.value||''})))}
async function load(){try{const r=await fetch(API+"?action=produk&t="+Date.now(),{cache:'no-store'});const j=await r.json();if(!j.success)throw Error(j.message||'API error');products=Array.isArray(j.data)?j.data:[];render();msg(products.length+' produk dimuat')}catch(e){msg('Gagal mengambil produk: '+e.message,true)}}
function addRows(){products.push({id:'',nama:'',kategori:'',hargaCoret:0,hargaDiskon:0,stok:0,gambar1:'',gambar2:'',gambar3:'',deskripsi:''});render();setTimeout(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'}),50)}
function collect(){return [...document.querySelectorAll('#productBody tr')].map(tr=>{const p={id:tr.dataset.id};tr.querySelectorAll('[data-k]').forEach(el=>p[el.dataset.k]=el.value);p.hargaCoret=Number(p.hargaCoret||0);p.hargaDiskon=Number(p.hargaDiskon||0);p.hargaJual=p.hargaDiskon;p.diskon=disc(p.hargaCoret,p.hargaDiskon);p.stok=Number(p.stok||0);return p}).filter(p=>p.nama.trim()||p.id)}
function postForm(payload){return new Promise((resolve,reject)=>{let iframe=document.getElementById('saveFrame');if(!iframe){iframe=document.createElement('iframe');iframe.name='saveFrame';iframe.id='saveFrame';iframe.style.display='none';document.body.appendChild(iframe)}const form=document.createElement('form');form.method='POST';form.action=API;form.target='saveFrame';form.style.display='none';Object.keys(payload).forEach(k=>{const input=document.createElement('input');input.type='hidden';input.name=k;input.value=typeof payload[k]==='string'?payload[k]:JSON.stringify(payload[k]);form.appendChild(input)});document.body.appendChild(form);form.submit();setTimeout(()=>{form.remove();resolve()},1200)})}
async function saveAll(){const items=collect();if(!items.length)return msg('Belum ada produk yang diisi.',true);const key=prompt('Masukkan kunci admin untuk menyimpan perubahan:');if(!key)return;const b=$('saveAll');b.disabled=true;b.textContent='⏳ Menyimpan...';try{await postForm({action:'saveProducts',key:key,products:items});msg(items.length+' produk dikirim. Memuat ulang...');await new Promise(r=>setTimeout(r,1200));await load()}catch(e){msg('Gagal mengirim: '+e.message,true)}finally{b.disabled=false;b.textContent='💾 Simpan'}}
function msg(t,error){const m=$('message');m.textContent=t;m.classList.remove('hidden');m.style.background=error?'#fdecec':'';clearTimeout(window.mt);window.mt=setTimeout(()=>m.classList.add('hidden'),4500)}
document.addEventListener('DOMContentLoaded',()=>{$('adminSearch').oninput=render;$('addRows').onclick=addRows;$('saveAll').onclick=saveAll;load()});
