"use strict";
(function(){
  const CART_KEY="dutaled_cart_v4", ORDERS_KEY="dutaled_orders";
  const SUPABASE_URL="https://opgeeqnucxrdqcgwcuge.supabase.co", SUPABASE_KEY="sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA";
  const headers={apikey:SUPABASE_KEY,Authorization:"Bearer "+SUPABASE_KEY,"Content-Type":"application/json"};
  const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
  const getCart=()=>{try{return JSON.parse(localStorage.getItem(CART_KEY)||"[]")||[]}catch(_){return[]}};
  const getOrders=()=>{try{return JSON.parse(localStorage.getItem(ORDERS_KEY)||"[]")||[]}catch(_){return[]}};
  const saveOrders=a=>localStorage.setItem(ORDERS_KEY,JSON.stringify(a.slice(0,50)));
  const getPrice=i=>Number(i.hargaTampil??i.hargaDiskon??i.hargaJual??i.harga??0)||0;
  const totalCart=c=>c.reduce((s,i)=>s+getPrice(i)*(Number(i.qty)||1),0);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  function closeCartPanel(){document.getElementById("cartClose")?.click();document.getElementById("cartOverlay")?.classList.add("hidden");document.getElementById("cartPanel")?.classList.remove("show","open","active")}
  function syncCartUI(){[document.getElementById("cartCount"),document.getElementById("bottomCartCount")].filter(Boolean).forEach(e=>e.textContent="0");if(document.getElementById("cartTotal"))document.getElementById("cartTotal").textContent=rupiah(0);if(document.getElementById("cartBox"))document.getElementById("cartBox").innerHTML='<div class="cart-empty">🛒 Keranjang masih kosong</div>';document.dispatchEvent(new CustomEvent("dutaled:cart-updated",{detail:{cart:[]}}))}
  async function rpc(name,body){const r=await fetch(SUPABASE_URL+"/rest/v1/rpc/"+name,{method:"POST",headers,body:JSON.stringify(body),cache:"no-store"});let j=null;try{j=await r.json()}catch(_){}if(!r.ok)throw new Error(j?.message||j?.hint||j?.details||j?.error||( "HTTP "+r.status));return j}
  function closeCheckout(){const m=document.getElementById("checkoutModal");if(m){m.classList.remove("show");m.setAttribute("aria-hidden","true")}document.body.classList.remove("checkout-open")}
  function renderSummary(){const c=getCart(),box=document.getElementById("checkoutItems"),t=totalCart(c);if(!box)return;box.innerHTML=c.map(i=>{const q=Number(i.qty)||1;return `<div class="checkout-item"><div><strong>${esc(i.nama||"Produk")}</strong><small>${q} × ${rupiah(getPrice(i))}</small></div><b>${rupiah(getPrice(i)*q)}</b></div>`}).join("");if(document.getElementById("checkoutSubtotal"))document.getElementById("checkoutSubtotal").textContent=rupiah(t);if(document.getElementById("checkoutGrandTotal"))document.getElementById("checkoutGrandTotal").textContent=rupiah(t)}
  function openCheckout(){if(!getCart().length){alert("Keranjang masih kosong.");return false}closeCartPanel();if(!document.getElementById("checkoutModal"))buildCheckoutModal();renderSummary();const m=document.getElementById("checkoutModal");if(m){m.classList.add("show");m.setAttribute("aria-hidden","false");document.body.classList.add("checkout-open");setTimeout(()=>document.querySelector("#checkoutModal input[name='nama']")?.focus(),80)}return true}
  window.openCheckout=openCheckout;window.closeCheckout=closeCheckout;
  async function submitOrder(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const cart=getCart();if(!cart.length){alert("Keranjang kosong.");return}const data=Object.fromEntries(new FormData(form).entries()),total=totalCart(cart),orderNo="DL"+new Date().toISOString().replace(/\D/g,"").slice(0,14)+Math.floor(Math.random()*90+10),btn=form.querySelector(".checkout-submit");if(btn){btn.disabled=true;btn.textContent="Menyimpan pesanan..."}try{const payload={order_id:orderNo,nama_pembeli:data.nama,no_hp:data.wa,alamat:data.alamat,kecamatan:data.kota||null,metode_pengiriman:data.pengiriman||null,metode_pembayaran:data.pembayaran||null,total_harga:total,status:"Menunggu Pembayaran"};const items=cart.map(i=>{const pid=Number(i.id);return{produk_id:Number.isFinite(pid)&&pid>0?String(pid):null,nama_produk:i.nama||"Produk",qty:Number(i.qty)||1,harga_saat_beli:Number(getPrice(i))||0}});const result=await rpc("create_public_order",{p_order:payload,p_items:items});if(!result?.success||!result?.id)throw new Error("Server tidak mengembalikan ID pesanan.");const order={id:result.id,orderNo:result.order_id||orderNo,createdAt:new Date().toISOString(),customer:data,items:cart,total,payment:data.pembayaran,status:"Menunggu Pembayaran"};localStorage.setItem("dutaled_last_order",JSON.stringify(order));saveOrders([order,...getOrders()]);localStorage.removeItem(CART_KEY);syncCartUI();closeCheckout();showSuccess(order);document.dispatchEvent(new CustomEvent("dutaled:order-created",{detail:order}))}catch(err){console.error("Supabase order RPC error",err);alert("Pesanan gagal disimpan: "+(err.message||err))}finally{if(btn){btn.disabled=false;btn.textContent="Buat Pesanan"}}}
  function paymentInfo(o){const p=String(o.payment||"").toLowerCase();if(p.includes("cod"))return{label:"COD",title:"Bayar saat barang diterima",status:"Menunggu diproses",amount:"Bayar saat barang sampai"};if(p.includes("qris"))return{label:"QRIS",title:"Nominal pembayaran",status:"Menunggu pembayaran",amount:rupiah(o.total)};return{label:"Transfer Bank",title:"Nominal transfer",status:"Menunggu pembayaran",amount:rupiah(o.total)}}
  function statusClass(s){const x=String(s||"").toLowerCase();return x.includes("selesai")?"done":x.includes("kirim")?"ship":x.includes("batal")?"cancel":x.includes("bayar")?"pay":"wait"}
  function customerAddress(o){const c=o.customer||{};return [c.alamat,c.kota].filter(Boolean).join(", ")}
  function showSuccess(o){document.getElementById("orderSuccess")?.remove();const pay=paymentInfo(o),items=o.items||[],address=customerAddress(o);document.body.insertAdjacentHTML("beforeend",`<div class="order-success" id="orderSuccess"><div class="order-success-page"><div class="order-success-top"><div class="order-success-icon">✓</div><span class="order-success-check">PESANAN TERSIMPAN</span><h2>Pesanan berhasil dibuat</h2><p>Pesanan Anda sudah masuk ke sistem Duta LED.</p></div><div class="order-card order-number-card"><span>Nomor pesanan</span><strong>${esc(o.orderNo)}</strong></div><div class="order-card customer-card"><h3>📍 Alamat Pengiriman</h3><strong>${esc(o.customer?.nama||"")}</strong><p>${esc(address||"Alamat belum tersedia")}</p><small>📱 ${esc(o.customer?.wa||"")}</small></div><div class="order-card"><h3>📦 Detail Pesanan</h3>${items.map(i=>{const q=Number(i.qty)||1,price=getPrice(i);return `<div class="order-detail-item"><div><strong>${esc(i.nama||"Produk")}</strong><small>${q} × ${rupiah(price)}</small></div><b>${rupiah(price*q)}</b></div>`}).join("")}<div class="order-total"><span>Total Pesanan</span><strong>${rupiah(o.total)}</strong></div></div><div class="order-card payment-card"><h3>💳 Pembayaran</h3><div class="payment-method"><span>Metode</span><strong>${esc(pay.label)}</strong></div><div class="payment-method"><span>Status</span><strong>${esc(pay.status)}</strong></div><div class="payment-amount"><span>${esc(pay.title)}</span><strong>${esc(pay.amount)}</strong></div>${pay.label==="Transfer Bank"?'<p>Silakan transfer sebesar <b>'+rupiah(o.total)+'</b> sesuai instruksi pembayaran Duta LED.</p>':''}${pay.label==="COD"?'<p>Pesanan dibayar saat barang diterima. Tidak perlu transfer sekarang.</p>':''}</div><div class="order-card status-card"><h3>📋 Status Pesanan</h3><div class="order-status"><span class="status-dot"></span><div><strong>${esc(o.status||"Menunggu Pembayaran")}</strong><small>Pesanan sudah dibuat dan menunggu proses berikutnya.</small></div></div></div><div class="order-success-actions"><button type="button" id="orderBackShop" class="checkout-submit">Kembali Belanja</button><button type="button" id="orderCloseSuccess" class="order-secondary">Tutup</button></div></div></div>`);document.body.classList.add("order-success-open");document.getElementById("orderCloseSuccess")?.addEventListener("click",closeSuccess);document.getElementById("orderBackShop")?.addEventListener("click",closeSuccess)}
  function closeSuccess(){document.getElementById("orderSuccess")?.remove();document.body.classList.remove("order-success-open");window.scrollTo({top:0,behavior:"smooth"})}
  function showOrders(){closeCartPanel();closeCheckout();document.getElementById("orderSuccess")?.remove();document.body.classList.remove("order-success-open");document.getElementById("ordersPage")?.remove();const orders=getOrders();document.body.insertAdjacentHTML("beforeend",`<div class="orders-page" id="ordersPage"><div class="orders-wrap"><div class="orders-head"><button type="button" id="ordersBack">‹</button><div><small>DUTA LED</small><h2>Pesanan Saya</h2></div></div>${orders.length?orders.map((o,idx)=>{const pay=paymentInfo(o),address=customerAddress(o);return `<article class="order-list-card"><div class="order-list-top"><div><span>Nomor pesanan</span><strong>${esc(o.orderNo)}</strong></div><b class="order-badge ${statusClass(o.status)}">${esc(o.status||"Menunggu Pembayaran")}</b></div><div class="order-list-address">📍 <span>${esc(o.customer?.nama||"")}<br>${esc(address||"Alamat belum tersedia")}</span></div><div class="order-list-items">${(o.items||[]).slice(0,3).map(i=>`<div><span>${esc(i.nama||"Produk")} × ${Number(i.qty)||1}</span><b>${rupiah(getPrice(i)*(Number(i.qty)||1))}</b></div>`).join("")}${(o.items||[]).length>3?`<small>+ ${(o.items||[]).length-3} produk lainnya</small>`:""}</div><div class="order-list-bottom"><span>${esc(pay.label)} • ${esc(pay.amount)}</span><strong>${rupiah(o.total)}</strong></div><button class="order-view-btn" type="button" data-order-index="${idx}">Lihat Detail Pesanan</button></article>`}).join(""):'<div class="orders-empty"><div>📦</div><h3>Belum ada pesanan</h3><p>Pesanan yang berhasil dibuat akan muncul di sini.</p><button type="button" id="ordersShop" class="checkout-submit">Mulai Belanja</button></div>'}</div></div>`);document.getElementById("ordersBack")?.addEventListener("click",()=>{document.getElementById("ordersPage")?.remove();window.scrollTo({top:0,behavior:"smooth")});document.getElementById("ordersShop")?.addEventListener("click",()=>{document.getElementById("ordersPage")?.remove();window.scrollTo({top:0,behavior:"smooth")});document.querySelectorAll(".order-view-btn").forEach(b=>b.addEventListener("click",()=>{const o=getOrders()[Number(b.dataset.orderIndex)];if(o){document.getElementById("ordersPage")?.remove();showSuccess(o)}}))}
  window.showOrders=showOrders;
  function buildCheckoutModal(){if(document.getElementById("checkoutModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="checkoutModal" class="checkout-modal" aria-hidden="true"><div class="checkout-backdrop" data-checkout-close></div><section class="checkout-dialog" role="dialog" aria-modal="true" aria-label="Checkout Duta LED"><header><div><small>CHECKOUT WEBSITE</small><h2>Buat Pesanan</h2></div><button type="button" class="checkout-x" data-checkout-close>×</button></header><form id="checkoutForm"><div class="checkout-grid"><div class="checkout-form-side"><h3>Data Pembeli</h3><label>Nama lengkap<input name="nama" required autocomplete="name" placeholder="Nama penerima"></label><label>Nomor HP / WhatsApp<input name="wa" required inputmode="tel" autocomplete="tel" placeholder="08xxxxxxxxxx"></label><label>Alamat lengkap<textarea name="alamat" required placeholder="Desa, jalan, nomor rumah"></textarea></label><label>Kota / Kecamatan<input name="kota" required placeholder="Contoh: Subah, Batang"></label><h3>Pengiriman</h3><select name="pengiriman"><option>JNE / J&T</option><option>SiCepat</option><option>POS Indonesia</option><option>Ambil di toko</option></select><h3>Pembayaran</h3><select name="pembayaran"><option>Transfer Bank</option><option>QRIS</option><option>COD jika tersedia</option></select></div><aside class="checkout-summary"><h3>Ringkasan Pesanan</h3><div id="checkoutItems"></div><div class="checkout-total"><span>Total Produk</span><b id="checkoutSubtotal">Rp0</b></div><p class="shipping-note">🚚 <b>Ongkir dibayar manual / COD.</b><br>Ongkir tidak ditambahkan ke total produk.</p><div class="checkout-grand"><span>Total Produk</span><strong id="checkoutGrandTotal">Rp0</strong></div><button type="submit" class="checkout-submit">Buat Pesanan</button><small>Pesanan dibuat langsung di website/database. WhatsApp hanya untuk konsultasi.</small></aside></div></form></section></div>`);document.querySelectorAll("[data-checkout-close]").forEach(x=>x.addEventListener("click",closeCheckout));document.getElementById("checkoutForm")?.addEventListener("submit",submitOrder)}
  function initCheckout(){
    const old=document.getElementById("checkoutButton");
    if(old){
      const b=old.cloneNode(true);
      b.removeAttribute("onclick");
      old.replaceWith(b);
      b.textContent="Checkout";
      b.type="button";
      b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();openCheckout()});
    }
    buildCheckoutModal();
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initCheckout);else initCheckout();
})();
