/* Duta LED — platform section + latest registered businesses */
(function(){
'use strict';
const SUPA='https://opgeeqnucxrdqcgwcuge.supabase.co',KEY='sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA';
function addStyle(){if(document.getElementById('platformSectionStyle'))return;const s=document.createElement('style');s.id='platformSectionStyle';s.textContent=`
.usaha-directory-cta{margin:20px 12px 24px!important;padding:0!important;background:transparent!important}.platform-inner{max-width:1100px;margin:auto;background:#fff;border:1px solid #eee;border-radius:18px;padding:20px 16px;box-shadow:0 3px 14px rgba(0,0,0,.06);box-sizing:border-box}.platform-head{text-align:center;max-width:760px;margin:0 auto 16px}.platform-head .eyebrow{font-size:11px;font-weight:800;letter-spacing:.7px;color:#e65f00}.platform-head h2{font-size:22px;line-height:1.2;margin:5px 0 8px}.platform-head p{font-size:13px;line-height:1.5;color:#666;margin:0}.platform-head p strong{color:#333}.platform-businesses{margin-top:18px}.platform-businesses-title{text-align:center;font-size:15px;font-weight:800;margin:0 0 9px}.platform-business-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.platform-business-card{display:block;text-decoration:none;color:inherit;border:1px solid #eee;border-radius:12px;background:#fff;padding:9px;min-width:0}.platform-business-logo{width:44px;height:44px;border-radius:10px;object-fit:cover;background:#f3f3f3;display:block;margin-bottom:7px}.platform-business-name{display:block;font-size:12px;font-weight:800;line-height:1.25}.platform-business-meta{display:block;font-size:10px;color:#777;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.platform-cta{display:block;width:max-content;margin:16px auto 0;text-align:center;text-decoration:none;padding:10px 16px!important;font-size:13px}.advantages{padding-top:10px!important}.advantages .section-title h2{font-size:21px}.advantages-grid{gap:9px!important}.advantage{padding:14px 10px!important;border-radius:13px!important}.advantage>div{font-size:22px!important}.advantage strong{font-size:13px!important}.advantage span{font-size:11px!important}.contact{padding-top:14px!important}.contact-box{padding:20px 14px!important}.contact-box h2{font-size:21px!important;margin:5px 0}.contact-box p{font-size:13px!important;line-height:1.45;margin:0 0 12px!important}.install-pwa{left:50%!important;right:auto!important;transform:translateX(-50%);bottom:calc(78px + env(safe-area-inset-bottom))!important;max-width:330px!important;width:calc(100% - 28px)!important;padding:10px!important}.install-pwa-icon{width:38px!important;height:38px!important;font-size:21px!important}.install-pwa-info strong{font-size:13px!important}.install-pwa-info small{font-size:10px!important}.install-pwa #installButton{padding:10px 14px!important;font-size:12px!important;border-radius:10px!important}
@media(max-width:699px){.usaha-directory-cta{margin:16px 8px 22px!important}.platform-inner{padding:17px 10px;border-radius:15px}.platform-head h2{font-size:19px}.platform-head p{font-size:12px}.platform-business-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.platform-business-card{padding:8px}.platform-business-logo{width:40px;height:40px}.platform-business-name{font-size:11px}.platform-business-meta{font-size:9px}.platform-cta{margin-top:13px!important}.advantages .section-title h2{font-size:19px}.advantage{padding:11px 7px!important}.advantage>div{font-size:20px!important}.advantage strong{font-size:12px!important}.advantage span{font-size:10px!important}.contact-box h2{font-size:19px!important}}
`;document.head.appendChild(s)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadBusinesses(box){try{if(!window.supabase?.createClient)return;const inner=box.querySelector('.platform-inner');if(!inner||inner.querySelector('.platform-businesses'))return;const d=window.supabase.createClient(SUPA,KEY);const{data,error}=await d.from('usaha').select('slug,nama_usaha,kategori,logo_url,alamat').eq('is_active',true).order('created_at',{ascending:false}).limit(8);if(error||!data?.length)return;const wrap=document.createElement('div');wrap.className='platform-businesses';wrap.innerHTML='<div class="platform-businesses-title">Usaha Anda Tampil di Sini</div><div class="platform-business-grid">'+data.map(u=>'<a class="platform-business-card" href="usaha.html?usaha='+encodeURIComponent(u.slug)+'"><img class="platform-business-logo" src="'+esc(u.logo_url||'image/no-image.png')+'" alt=""><span class="platform-business-name">'+esc(u.nama_usaha||'Usaha')+'</span><span class="platform-business-meta">'+esc((u.kategori||'')+(u.alamat?' · '+u.alamat:''))+'</span></a>').join('')+'</div>';inner.appendChild(wrap)}catch(e){}}
function boot(){
const boxes=[...document.querySelectorAll('.usaha-directory-cta')];if(!boxes.length)return;
const box=boxes[0];
boxes.slice(1).forEach(x=>x.remove());
box.dataset.platformReady='1';
addStyle();
box.innerHTML='<div class="platform-inner"><div class="platform-head"><span class="eyebrow">DUTA LED</span><h2>🤝 SATU WEBSITE, BANYAK KEGUNAAN</h2><p><strong>Usaha Anda Tampil di Sini — GRATIS.</strong><br>Masukkan nama usaha, foto/logo, alamat, WhatsApp, jam buka, media sosial, produk/jasa, harga dan promo. Setelah didaftarkan, usaha Anda langsung bisa ditampilkan dan dibagikan.</p></div><a class="usaha-add platform-cta" href="usaha.html">➕ Daftar & Lihat Usaha</a></div>';
loadBusinesses(box)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
