/* DUTA LED - Direktori Usaha Publik v3 */
(function(){
'use strict';
const SUPA='https://opgeeqnucxrdqcgwcuge.supabase.co',KEY='sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA';let client=null;
function db(){if(client)return client;if(!window.supabase?.createClient)return null;return client=window.supabase.createClient(SUPA,KEY)}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function slugify(s){return(s||'').toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'usaha'}
async function uniqueSlug(base){let s=base,n=1,d=db();while(true){const{data}=await d.from('usaha').select('id').eq('slug',s).maybeSingle();if(!data)return s;s=base+'-'+(++n)}}
function openForm(){
 if(document.getElementById('usahaFormModal'))return;
 const m=document.createElement('div');m.id='usahaFormModal';m.innerHTML=`<div class="usaha-backdrop"></div><div class="usaha-modal-box"><button class="usaha-close" type="button">×</button><div class="usaha-head"><span>🚀</span><div><h2>Daftarkan Usaha</h2><p>Gratis • Langsung tampil • Dapat link usaha</p></div></div><form id="usahaForm"><input name="nama_usaha" required placeholder="Nama usaha *"><select name="kategori"><option>Toko</option><option>Kuliner</option><option>Jasa</option><option>Bengkel</option><option>Percetakan</option><option>Fashion</option><option>Kreator</option><option>Event</option><option>Lainnya</option></select><input name="logo_url" type="url" placeholder="URL foto/logo (opsional)"><textarea name="deskripsi" placeholder="Deskripsi singkat usaha"></textarea><input name="whatsapp" placeholder="WhatsApp"><input name="alamat" placeholder="Alamat"><input name="maps_url" type="url" placeholder="Link Google Maps"><input name="jam_buka" placeholder="Jam buka, contoh 08.00–21.00"><input name="instagram" placeholder="Instagram (opsional)"><input name="facebook" placeholder="Facebook (opsional)"><input name="tiktok" placeholder="TikTok (opsional)"><textarea name="produk_text" placeholder="Produk / layanan dan harga"></textarea><textarea name="promo_text" placeholder="Promo saat ini (opsional)"></textarea><button class="usaha-submit" type="submit">🚀 Tampilkan Usaha Saya</button><div id="usahaFormMsg"></div></form></div>`;
 document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.usaha-close').onclick=close;m.querySelector('.usaha-backdrop').onclick=close;
 m.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,msg=m.querySelector('#usahaFormMsg'),btn=f.querySelector('.usaha-submit');btn.disabled=true;msg.textContent='Menyimpan...';try{const o=Object.fromEntries(new FormData(f).entries()),d=db();if(!d)throw Error('Database belum siap');o.slug=await uniqueSlug(slugify(o.nama_usaha));const{data,error}=await d.from('usaha').insert(o).select('slug').single();if(error)throw error;msg.textContent='Usaha berhasil ditampilkan!';setTimeout(()=>location.href='usaha.html?usaha='+encodeURIComponent(data.slug),250)}catch(err){msg.textContent='Gagal menyimpan: '+(err.message||err);btn.disabled=false}};
}
async function loadDirectory(){const grid=document.getElementById('usahaGrid'),status=document.getElementById('usahaDirectoryStatus'),d=db();if(!grid||!d)return;if(status)status.textContent='Memuat usaha...';const{data,error}=await d.from('usaha').select('*').eq('is_active',true).order('created_at',{ascending:false});if(error){if(status)status.textContent='Gagal memuat daftar usaha.';return}if(status)status.textContent=data.length?`${data.length} usaha terdaftar`:'Belum ada usaha. Jadilah yang pertama!';grid.innerHTML=data.map(x=>`<a class="usaha-card" href="usaha.html?usaha=${encodeURIComponent(x.slug)}"><div class="usaha-card-media">${x.logo_url?`<img src="${esc(x.logo_url)}" alt="${esc(x.nama_usaha)}">`:'<div class="usaha-card-logo">🏪</div>'}</div><div class="usaha-card-body"><span class="usaha-card-cat">${esc(x.kategori)}</span><h3>${esc(x.nama_usaha)}</h3>${x.deskripsi?`<p>${esc(x.deskripsi)}</p>`:''}${x.alamat?`<small>📍 ${esc(x.alamat)}</small>`:''}<span class="usaha-card-link">Lihat halaman usaha →</span></div></a>`).join('')}
async function showPublic(slug){const d=db();if(!d)return;const{data,error}=await d.from('usaha').select('*').eq('slug',slug).eq('is_active',true).maybeSingle();if(error||!data)return;const app=document.getElementById('usahaPage');if(!app)return;app.innerHTML=`<div class="usaha-public-inner"><a class="usaha-back" href="usaha.html">← Daftar Usaha</a><div class="usaha-profile">${data.logo_url?`<img src="${esc(data.logo_url)}" alt="${esc(data.nama_usaha)}">`:'<div class="usaha-logo">🏪</div>'}<span>${esc(data.kategori)}</span><h1>${esc(data.nama_usaha)}</h1><p>${esc(data.deskripsi||'')}</p><div class="usaha-actions">${data.whatsapp?`<a href="https://wa.me/${data.whatsapp.replace(/\D/g,'')}">💬 WhatsApp</a>`:''}${data.maps_url?`<a href="${esc(data.maps_url)}" target="_blank" rel="noopener">📍 Lokasi</a>`:''}</div></div><div class="usaha-info">${data.produk_text?`<h2>Produk / Layanan</h2><p>${esc(data.produk_text).replace(/\n/g,'<br>')}</p>`:''}${data.promo_text?`<h2>🎉 Promo</h2><p>${esc(data.promo_text).replace(/\n/g,'<br>')}</p>`:''}${data.alamat?`<p>📍 ${esc(data.alamat)}</p>`:''}${data.jam_buka?`<p>🕒 ${esc(data.jam_buka)}</p>`:''}${data.instagram||data.facebook||data.tiktok?'<div class="usaha-social">'+(data.instagram?`<a href="${esc(data.instagram)}" target="_blank">Instagram</a>`:'')+(data.facebook?`<a href="${esc(data.facebook)}" target="_blank">Facebook</a>`:'')+(data.tiktok?`<a href="${esc(data.tiktok)}" target="_blank">TikTok</a>`:'')+'</div>':''}</div><div class="usaha-footer"><strong>🤝 Satu Website, Banyak Kegunaan</strong><p>Promosikan usaha Anda dan temukan usaha lainnya di Duta LED.</p><a class="usaha-main-btn" href="usaha.html">Lihat Usaha Lain</a><button type="button" id="daftarUsahaFromPage">➕ Daftarkan Usaha Anda</button></div></div>`;document.title=data.nama_usaha+' | Duta LED';app.classList.remove('hidden');document.getElementById('usahaDirectory')?.classList.add('hidden');document.getElementById('usahaHero')?.classList.add('hidden');document.getElementById('daftarUsahaFromPage').onclick=openForm}
function boot(){const slug=new URLSearchParams(location.search).get('usaha');if(document.getElementById('usahaGrid'))loadDirectory();if(slug)showPublic(slug)}
window.openUsahaForm=openForm;window.loadUsahaDirectory=loadDirectory;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();