/* DUTA LED - Direktori Usaha Publik v2 */
(function(){
  const SUPA='https://opgeeqnucxrdqcgwcuge.supabase.co';
  const KEY='sb_publishable_uqah55SK8ZjyugWprFnFMA_QnyVdCLA';
  let client=null;
  function getClient(){if(client)return client;if(!window.supabase?.createClient)return null;client=window.supabase.createClient(SUPA,KEY);return client;}
  function slugify(s){return(s||'').toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'usaha';}
  async function uniqueSlug(base){const db=getClient();let slug=base,n=1;while(true){const{data}=await db.from('usaha').select('id').eq('slug',slug).maybeSingle();if(!data)return slug;slug=base+'-'+(++n);}}
  function openForm(){
    if(document.getElementById('usahaFormModal'))return;
    const m=document.createElement('div');m.id='usahaFormModal';m.innerHTML=`<div class="usaha-backdrop"></div><div class="usaha-modal"><button class="usaha-close" type="button">×</button><div class="usaha-head"><span>🚀</span><div><h2>Daftarkan Usaha</h2><p>Gratis • Langsung tampil • Dapat link usaha</p></div></div><form id="usahaForm"><input name="nama_usaha" required placeholder="Nama usaha *"><select name="kategori"><option>Toko</option><option>Kuliner</option><option>Jasa</option><option>Bengkel</option><option>Percetakan</option><option>Fashion</option><option>Kreator</option><option>Event</option><option>Lainnya</option></select><input name="logo_url" type="url" placeholder="URL foto/logo (opsional)"><textarea name="deskripsi" placeholder="Deskripsi singkat usaha"></textarea><input name="whatsapp" placeholder="WhatsApp"><input name="alamat" placeholder="Alamat"><input name="maps_url" type="url" placeholder="Link Google Maps"><input name="jam_buka" placeholder="Jam buka, contoh 08.00–21.00"><input name="instagram" placeholder="Instagram (opsional)"><input name="facebook" placeholder="Facebook (opsional)"><input name="tiktok" placeholder="TikTok (opsional)"><textarea name="produk_text" placeholder="Produk / layanan dan harga, contoh: Servis TV - Rp50.000"></textarea><textarea name="promo_text" placeholder="Promo saat ini (opsional)"></textarea><button class="usaha-submit" type="submit">🚀 Tampilkan Usaha Saya</button><div id="usahaFormMsg"></div></form></div>`;
    document.body.appendChild(m);const close=()=>m.remove();m.querySelector('.usaha-close').onclick=close;m.querySelector('.usaha-backdrop').onclick=close;
    m.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,msg=m.querySelector('#usahaFormMsg'),btn=f.querySelector('button[type=submit]');btn.disabled=true;msg.textContent='Menyimpan...';try{const o=Object.fromEntries(new FormData(f).entries());const db=getClient();if(!db)throw Error('Database belum siap');o.slug=await uniqueSlug(slugify(o.nama_usaha));const{data,error}=await db.from('usaha').insert(o).select('slug').single();if(error)throw error;const url=location.origin+location.pathname+'?usaha='+encodeURIComponent(data.slug);msg.innerHTML='<strong>Usaha berhasil ditampilkan!</strong><br><a href="'+url+'">Buka halaman usaha sekarang</a> · <button type="button" id="usahaShare">Bagikan</button>';m.querySelector('#usahaShare').onclick=()=>navigator.share?navigator.share({title:o.nama_usaha,url}):navigator.clipboard?.writeText(url);setTimeout(()=>location.href=url,350);}catch(err){msg.textContent='Gagal menyimpan: '+(err.message||err);btn.disabled=false;}};
  }
  async function showPublic(slug){
    const db=getClient();if(!db)return;const{data,error}=await db.from('usaha').select('*').eq('slug',slug).eq('is_active',true).maybeSingle();if(error||!data)return;
    const app=document.getElementById('storeApp');if(!app)return;const box=document.createElement('section');box.className='usaha-public';box.innerHTML='<div class="usaha-public-inner"><a class="usaha-back" href="'+location.pathname+'">← Duta LED</a><div class="usaha-profile">'+(data.logo_url?'<img src="'+esc(data.logo_url)+'" alt="">':'<div class="usaha-logo">🏪</div>')+'<span>'+esc(data.kategori)+'</span><h1>'+esc(data.nama_usaha)+'</h1><p>'+esc(data.deskripsi||'')+'</p><div class="usaha-actions">'+(data.whatsapp?'<a href="https://wa.me/'+data.whatsapp.replace(/\D/g,'')+'">💬 WhatsApp</a>':'')+(data.maps_url?'<a href="'+esc(data.maps_url)+'">📍 Lokasi</a>':'')+'</div></div><div class="usaha-info">'+(data.produk_text?'<h2>Produk / Layanan</h2><p>'+esc(data.produk_text).replace(/\n/g,'<br>')+'</p>':'')+(data.promo_text?'<h2>🎉 Promo</h2><p>'+esc(data.promo_text).replace(/\n/g,'<br>')+'</p>':'')+(data.alamat?'<p>📍 '+esc(data.alamat)+'</p>':'')+(data.jam_buka?'<p>🕒 '+esc(data.jam_buka)+'</p>':'')+'</div><div class="usaha-footer"><strong>Temukan usaha lainnya di Duta LED</strong><br><button type="button" id="daftarUsahaFromPage">➕ Daftarkan Usaha Anda</button></div></div>';app.innerHTML='';app.appendChild(box);document.title=data.nama_usaha+' | Duta LED';box.querySelector('#daftarUsahaFromPage').onclick=openForm;
  }
  function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  window.openUsahaForm=openForm;
  document.addEventListener('DOMContentLoaded',()=>{const slug=new URLSearchParams(location.search).get('usaha');if(slug){setTimeout(()=>showPublic(slug),1200);setTimeout(()=>showPublic(slug),3000);}});
})();