(()=>{'use strict';
const KEY='DUTA_WALLET_V3',OLD='DUTA_WALLET_V2';
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function load(){try{let d=JSON.parse(localStorage.getItem(KEY)||'null');if(!d){const o=JSON.parse(localStorage.getItem(OLD)||'null');d=o&&typeof o==='object'?o:{}}return{tx:Array.isArray(d.tx)?d.tx:[],debt:Array.isArray(d.debt)?d.debt:[],bill:Array.isArray(d.bill)?d.bill:[]}}catch{return{tx:[],debt:[],bill:[]}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function totals(tx,from=null){return tx.filter(x=>!from||x.date>=from).reduce((a,x)=>{a[x.type]=(a[x.type]||0)+Number(x.amount||0);return a},{in:0,out:0})}
function monthStart(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-01`}
function weekStart(){const d=new Date();d.setDate(d.getDate()-6);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function render(){const root=document.querySelector('#walletApp .wallet-wrap');if(!root)return;const d=load(),all=totals(d.tx),day=totals(d.tx,today()),debt=d.debt.reduce((a,x)=>a+Math.max(0,Number(x.amount)-Number(x.paid||0)),0),bill=d.bill.reduce((a,x)=>a+Math.max(0,Number(x.amount)-Number(x.paid||0)),0);root.innerHTML=`<div class="wallet-top"><div><div class="wallet-title">👛 Wallet</div><div class="wallet-sub">Keuangan pribadi & toko</div></div></div><button class="wallet-store-btn" type="button" onclick="window.showStore?.()">🛍️ Kembali ke Toko</button><div class="wallet-dashboard"><div class="wallet-balance"><span>💵 SALDO SAAT INI</span><strong>${money(all.in-all.out)}</strong></div><div class="wallet-today"><button class="wallet-today-card in wallet-card-button" data-nav="in"><small>💰 Uang Masuk Hari Ini</small><strong>${money(day.in)}</strong><em>＋ Tambah</em></button><button class="wallet-today-card out wallet-card-button" data-nav="out"><small>💸 Uang Keluar Hari Ini</small><strong>${money(day.out)}</strong><em>＋ Tambah</em></button></div><div class="wallet-summary-cards"><button class="wallet-today-card debt wallet-card-button" data-nav="debt"><small>🤝 Hutang</small><strong>${money(debt)}</strong><em>Lihat / Tambah</em></button><button class="wallet-today-card bill wallet-card-button" data-nav="bill"><small>🧾 Tagihan</small><strong>${money(bill)}</strong><em>Lihat / Tambah</em></button></div></div><nav class="wallet-quick-nav wallet-main-nav"><button data-nav="summary">🏠<small>Ringkasan</small></button><button data-nav="in">💰<small>Uang Masuk</small></button><button data-nav="out">💸<small>Uang Keluar</small></button><button data-nav="debt">🤝<small>Hutang</small></button><button data-nav="bill">🧾<small>Tagihan</small></button><button data-nav="report">📊<small>Laporan</small></button></nav><section class="wallet-section" id="walletSummarySection"><h3>🕘 Riwayat Transaksi</h3><div id="walletHistory"></div></section><section class="wallet-section" id="walletDebtSection" hidden><h3>🤝 Hutang</h3><button class="wallet-add-full" id="walletAddDebt">＋ Tambah Hutang</button><div id="walletDebtList"></div></section><section class="wallet-section" id="walletBillSection" hidden><h3>🧾 Tagihan</h3><button class="wallet-add-full" id="walletAddBill">＋ Tambah Tagihan</button><div id="walletBillList"></div></section><section class="wallet-section" id="walletReportSection" hidden><h3>📊 Laporan Keuangan</h3><div class="wallet-periods"><button class="wallet-period active" data-period="today">Hari Ini</button><button class="wallet-period" data-period="week">7 Hari</button><button class="wallet-period" data-period="month">Bulan Ini</button></div><div id="walletReport"></div></section>`;bind();refreshLists(d)}
function bind(){document.querySelectorAll('.wallet-main-nav [data-nav],.wallet-card-button[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='in')formTx('in');else if(n==='out')formTx('out');else showSection(n)});document.getElementById('walletAddDebt').onclick=()=>formRecord('debt');document.getElementById('walletAddBill').onclick=()=>formRecord('bill');document.querySelectorAll('.wallet-period').forEach(b=>b.onclick=()=>{document.querySelectorAll('.wallet-period').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawReport(load(),b.dataset.period)})}
function showSection(k){const ids={summary:'walletSummarySection',debt:'walletDebtSection',bill:'walletBillSection',report:'walletReportSection'};Object.values(ids).forEach(id=>{const x=document.getElementById(id);if(x)x.hidden=true});const el=document.getElementById(ids[k]||ids.summary);if(el){el.hidden=false;el.scrollIntoView({behavior:'smooth',block:'start'})}}
function refreshLists(d){drawHistory(d);drawDebtBill(d);drawReport(d,'today')}
function drawHistory(d){const el=document.getElementById('walletHistory');if(!el)return;el.innerHTML=d.tx.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,100).map(x=>`<div class="wallet-item"><div><b>${esc(x.category||'Lainnya')}</b><small>${esc(x.date||'')}${x.note?' · '+esc(x.note):''}</small></div><strong class="${x.type}">${x.type==='in'?'+':'−'} ${money(x.amount)}</strong></div>`).join('')||'<div class="wallet-empty">Belum ada transaksi.</div>'}
function drawDebtBill(d){const de=document.getElementById('walletDebtList'),bi=document.getElementById('walletBillList');if(de)de.innerHTML=d.debt.map(x=>`<div class="wallet-item"><div><b>${esc(x.name)}</b><small>Total ${money(x.amount)} · Sisa ${money(Number(x.amount)-Number(x.paid||0))}</small></div><button class="wallet-mini-btn" onclick="window.payWallet('debt',${x.id})">Bayar</button></div>`).join('')||'<div class="wallet-empty">Belum ada hutang.</div>';if(bi)bi.innerHTML=d.bill.map(x=>`<div class="wallet-item"><div><b>${esc(x.name)}</b><small>Total ${money(x.amount)} · Jatuh tempo ${esc(x.due||x.date)} · Sisa ${money(Number(x.amount)-Number(x.paid||0))}</small></div><button class="wallet-mini-btn" onclick="window.payWallet('bill',${x.id})">Bayar</button></div>`).join('')||'<div class="wallet-empty">Belum ada tagihan.</div>'}
function drawReport(d,p){const from=p==='month'?monthStart():p==='week'?weekStart():today(),t=totals(d.tx,from),el=document.getElementById('walletReport');if(el)el.innerHTML=`<div class="wallet-report"><div><small>Uang Masuk</small><b>${money(t.in)}</b></div><div><small>Uang Keluar</small><b>${money(t.out)}</b></div><div><small>Selisih</small><b>${money(t.in-t.out)}</b></div></div>`}
function modal(html,saveFn){const f=document.createElement('div');f.className='wallet-modal';f.innerHTML=`<div class="wallet-modal-card"><button class="wallet-modal-close" type="button">×</button>${html}</div>`;document.body.appendChild(f);f.querySelector('.wallet-modal-close').onclick=()=>f.remove();saveFn(f,()=>{f.remove();render()})}
function formTx(type){modal(`<h3>${type==='in'?'💰 Uang Masuk':'💸 Uang Keluar'}</h3><label>Jumlah<input class="wallet-input" id="wfAmount" type="number" min="1" inputmode="numeric"></label><label>Kategori<input class="wallet-input" id="wfCat" value="${type==='in'?'Penjualan':'Keperluan'}"></label><label>Tanggal<input class="wallet-input" id="wfDate" type="date" value="${today()}"></label><label>Keterangan<input class="wallet-input" id="wfNote"></label><button class="wallet-save" id="wfSave">Simpan</button>`,(f,close)=>f.querySelector('#wfSave').onclick=()=>{const amount=Number(f.querySelector('#wfAmount').value);if(amount<=0)return alert('Jumlah wajib diisi.');const d=load();d.tx.push({id:Date.now(),type,amount,category:f.querySelector('#wfCat').value.trim()||'Lainnya',note:f.querySelector('#wfNote').value.trim(),date:f.querySelector('#wfDate').value||today()});save(d);close()})}
function formRecord(key){const bill=key==='bill';modal(`<h3>${bill?'🧾 Tambah Tagihan':'🤝 Tambah Hutang'}</h3><label>Nama / Keterangan<input class="wallet-input" id="wfName" placeholder="${bill?'Contoh: PLN':'Contoh: Pinjaman teman'}"></label><label>Jumlah<input class="wallet-input" id="wfAmount" type="number" min="1" inputmode="numeric"></label><label>Tanggal<input class="wallet-input" id="wfDate" type="date" value="${today()}"></label>${bill?'<label>Jatuh Tempo<input class="wallet-input" id="wfDue" type="date"></label>':''}<button class="wallet-save" id="wfSave">Simpan</button>`,(f,close)=>f.querySelector('#wfSave').onclick=()=>{const name=f.querySelector('#wfName').value.trim(),amount=Number(f.querySelector('#wfAmount').value);if(!name||amount<=0)return alert('Nama dan jumlah wajib diisi.');const d=load(),x={id:Date.now(),name,amount,paid:0,date:f.querySelector('#wfDate').value||today()};if(bill)x.due=f.querySelector('#wfDue').value||x.date;d[key].push(x);save(d);close()})}
window.payWallet=(key,id)=>{const d=load(),x=d[key].find(v=>String(v.id)===String(id));if(!x)return;const sisa=Math.max(0,Number(x.amount)-Number(x.paid||0));const n=Number(prompt(`Sisa ${money(sisa)}. Masukkan pembayaran:`,sisa)||0);if(n<=0)return;x.paid=Math.min(Number(x.amount),Number(x.paid||0)+n);d.tx.push({id:Date.now(),type:'out',amount:n,category:key==='debt'?'Bayar Hutang':'Bayar Tagihan',note:x.name,date:today()});save(d);render()};
window.renderWallet=render;window.walletAddIn=()=>formTx('in');window.walletAddOut=()=>formTx('out');
function init(){if(document.getElementById('walletApp'))render()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();