(()=>{'use strict';
const KEY='DUTA_WALLET_V2';
const get=()=>{try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');return{tx:Array.isArray(d.tx)?d.tx:[],debt:Array.isArray(d.debt)?d.debt:[],bill:Array.isArray(d.bill)?d.bill:[]}}catch{return{tx:[],debt:[],bill:[]}}};
const put=d=>localStorage.setItem(KEY,JSON.stringify(d));
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function refresh(){window.renderWallet?.(window.walletPeriodName||'today')}
function modal(kind){const isBill=kind==='bill',f=document.createElement('div');f.className='wallet-modal';f.innerHTML=`<div class="wallet-modal-card"><button class="wallet-modal-close" type="button">×</button><h3>${isBill?'🧾 Tambah Tagihan':'🤝 Tambah Hutang'}</h3><label>Nama / keterangan<input id="wfName" class="wallet-input" type="text" placeholder="Contoh: PLN / Pinjaman teman"></label><label>Jumlah<input id="wfAmount" class="wallet-input" type="number" inputmode="numeric" min="1" placeholder="Rp 0"></label><label>Tanggal<input id="wfDate" class="wallet-input" type="date" value="${today()}"></label>${isBill?'<label>Jatuh tempo<input id="wfDue" class="wallet-input" type="date"></label>':''}<button id="wfSave" class="wallet-save" type="button">Simpan ${isBill?'Tagihan':'Hutang'}</button></div>`;document.body.appendChild(f);f.querySelector('.wallet-modal-close').onclick=()=>f.remove();f.addEventListener('click',e=>{if(e.target===f)f.remove()});f.querySelector('#wfSave').onclick=()=>{const name=f.querySelector('#wfName').value.trim(),amount=Number(f.querySelector('#wfAmount').value);if(!name||amount<=0){alert('Nama dan jumlah wajib diisi.');return}const d=get(),x={id:Date.now(),name,amount,paid:0,date:f.querySelector('#wfDate').value||today()};if(isBill)x.due=f.querySelector('#wfDue').value||x.date;d[isBill?'bill':'debt'].push(x);put(d);f.remove();refresh()};setTimeout(()=>f.querySelector('#wfName')?.focus(),50)}
function setup(){document.querySelectorAll('#walletAddDebt').forEach(b=>{b.onclick=e=>{e.preventDefault();modal('debt')}});document.querySelectorAll('#walletAddBill').forEach(b=>{b.onclick=e=>{e.preventDefault();modal('bill')}});document.addEventListener('click',e=>{const tab=e.target.closest('[data-wallet-tab]');if(!tab)return;const page=tab.dataset.walletTab;document.querySelectorAll('[data-wallet-page]').forEach(x=>x.hidden=x.dataset.walletPage!==page);if(page==='home'||page==='report')document.querySelectorAll('[data-wallet-page]').forEach(x=>x.hidden=true);document.querySelectorAll('.wallet-quick-nav button').forEach(x=>x.classList.toggle('active',x===tab));});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();