(()=>{'use strict';
const KEY='DUTA_WALLET_V3',OLD='DUTA_WALLET_V2';let storage='localStorage';
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const pad=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const nowDT=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`};
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
function storageTest(){try{const k='__duta_wallet_test__';localStorage.setItem(k,'1');if(localStorage.getItem(k)==='1'){localStorage.removeItem(k);storage='localStorage';return true}}catch(e){}try{const k='__duta_wallet_test__';sessionStorage.setItem(k,'1');if(sessionStorage.getItem(k)==='1'){sessionStorage.removeItem(k);storage='sessionStorage';return true}}catch(e){}storage='none';return false}
function get(k){try{return storage==='sessionStorage'?sessionStorage.getItem(k):localStorage.getItem(k)}catch(e){return null}}
function put(k,v){try{if(storage==='sessionStorage')sessionStorage.setItem(k,v);else localStorage.setItem(k,v);return true}catch(e){return false}}
function load(){try{let d=JSON.parse(get(KEY)||'null');if(!d){const o=JSON.parse(get(OLD)||'null');d=o&&typeof o==='object'?o:{}}return{tx:Array.isArray(d.tx)?d.tx:[],debt:Array.isArray(d.debt)?d.debt:[],bill:Array.isArray(d.bill)?d.bill:[]}}catch(e){return{tx:[],debt:[],bill:[]}}}
function save(d){const raw=JSON.stringify(d);if(put(KEY,raw)&&get(KEY)===raw)return true;alert('Browser menolak penyimpanan Wallet. Izinkan data situs/cookies untuk dutaled.my.id.');return false}
function modal(title,html,onReady){const f=document.createElement('div');f.className='wallet-modal';f.innerHTML=`<div class="wallet-modal-card"><div class="wallet-modal-head"><h3>${title}</h3><button type="button" class="wallet-modal-close">×</button></div>${html}</div>`;document.body.appendChild(f);const close=()=>f.remove();f.querySelector('.wallet-modal-close').onclick=close;onReady?.(f,close)}
function formTx(type){modal(type==='masuk'?'💰 Uang Masuk':'💸 Uang Keluar',`<label>Kategori<input class="wallet-input" id="wfKategori" placeholder="Contoh: Penjualan / Makan / Listrik"></label><label>Jumlah<input class="wallet-input" id="wfJumlah" type="number" min="1" placeholder="0"></label><label>Tanggal<input class="wallet-input" id="wfTanggal" type="datetime-local"></label><label>Keterangan<input class="wallet-input" id="wfKet" placeholder="Opsional"></label><button type="button" class="wallet-save" id="wfSave">Simpan Transaksi</button>`,(f,close)=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());f.querySelector('#wfTanggal').value=d.toISOString().slice(0,16);f.querySelector('#wfSave').onclick=()=>{const kategori=f.querySelector('#wfKategori').value.trim();const jumlah=Number(f.querySelector('#wfJumlah').value||0);if(!kategori)return alert('Kategori wajib diisi.');if(jumlah<=0)return alert('Jumlah harus lebih dari Rp0.');const data=load();data.tx.push({id:Date.now(),jenis:type,tanggal:f.querySelector('#wfTanggal').value?new Date(f.querySelector('#wfTanggal').value).toISOString():new Date().toISOString(),kategori,jumlah,keterangan:f.querySelector('#wfKet').value.trim()});if(save(data)){close();render();alert('Transaksi tersimpan.')}}})}
window.openWalletForm=formTx;
function openDebtForm(){modal('🤝 Hutang',`<label>Nama<input class="wallet-input" id="wdNama" placeholder="Nama orang / sumber hutang"></label><label>Jumlah<input class="wallet-input" id="wdJumlah" type="number" min="1" placeholder="0"></label><label>Jatuh Tempo<input class="wallet-input" id="wdDue" type="date"></label><label>Keterangan<input class="wallet-input" id="wdKet" placeholder="Opsional"></label><button type="button" class="wallet-save" id="wdSave">Simpan Hutang</button>`,(f,close)=>{f.querySelector('#wdSave').onclick=()=>{const nama=f.querySelector('#wdNama').value.trim(),jumlah=Number(f.querySelector('#wdJumlah').value||0);if(!nama||jumlah<=0)return alert('Nama dan jumlah wajib diisi.');const d=load();d.debt.push({id:Date.now(),nama,jumlah,terbayar:0,jatuhTempo:f.querySelector('#wdDue').value||null,keterangan:f.querySelector('#wdKet').value.trim(),createdAt:nowDT()});if(save(d)){close();render();alert('Hutang tersimpan.')}}})}
window.openDebtForm=openDebtForm;
function openBillForm(){modal('🧾 Tagihan',`<label>Nama Tagihan<input class="wallet-input" id="wbNama" placeholder="Contoh: PLN / Internet"></label><label>Jumlah<input class="wallet-input" id="wbJumlah" type="number" min="1" placeholder="0"></label><label>Jatuh Tempo<input class="wallet-input" id="wbDue" type="date"></label><label>Keterangan<input class="wallet-input" id="wbKet" placeholder="Opsional"></label><button type="button" class="wallet-save" id="wbSave">Simpan Tagihan</button>`,(f,close)=>{f.querySelector('#wbSave').onclick=()=>{const nama=f.querySelector('#wbNama').value.trim(),jumlah=Number(f.querySelector('#wbJumlah').value||0);if(!nama||jumlah<=0)return alert('Nama dan jumlah wajib diisi.');const d=load();d.bill.push({id:Date.now(),nama,jumlah,terbayar:0,jatuhTempo:f.querySelector('#wbDue').value||null,keterangan:f.querySelector('#wbKet').value.trim(),createdAt:nowDT()});if(save(d)){close();render();alert('Tagihan tersimpan.')}}})}
window.openBillForm=openBillForm;
function payDebt(id){const d=load(),x=d.debt.find(v=>String(v.id)===String(id));if(!x)return;const sisa=Math.max(0,x.jumlah-(x.terbayar||0));const n=Number(prompt(`Bayar hutang ${x.nama}. Sisa ${money(sisa)}`,sisa)||0);if(n<=0||n>sisa)return;x.terbayar=(x.terbayar||0)+n;d.tx.push({id:Date.now(),jenis:'keluar',tanggal:new Date().toISOString(),kategori:'Bayar Hutang',jumlah:n,keterangan:x.nama});if(save(d))render()}
function payBill(id){const d=load(),x=d.bill.find(v=>String(v.id)===String(id));if(!x)return;const sisa=Math.max(0,x.jumlah-(x.terbayar||0));const n=Number(prompt(`Bayar tagihan ${x.nama}. Sisa ${money(sisa)}`,sisa)||0);if(n<=0||n>sisa)return;x.terbayar=(x.terbayar||0)+n;d.tx.push({id:Date.now(),jenis:'keluar',tanggal:new Date().toISOString(),kategori:'Bayar Tagihan',jumlah:n,keterangan:x.nama});if(save(d))render()}
function listSpecial(kind){const d=load(),arr=kind==='debt'?d.debt:d.bill;modal(kind==='debt'?'🤝 Daftar Hutang':'🧾 Daftar Tagihan',`<button type="button" class="wallet-save" id="specialAdd">＋ Tambah</button><div id="specialList" class="wallet-special-list"></div>`,(f,close)=>{const draw=()=>{const fresh=load()[kind==='debt'?'debt':'bill'];arr.splice(0,arr.length,...fresh);f.querySelector('#specialList').innerHTML=arr.length?arr.slice().reverse().map(x=>{const total=Number(x.jumlah||0),paid=Number(x.terbayar||0),sisa=Math.max(0,total-paid);return `<div class="wallet-special-row"><div><b>${esc(x.nama)}</b><small>${esc(x.keterangan||'')} ${x.jatuhTempo?'· Jatuh tempo '+esc(x.jatuhTempo):''}</small><small>${sisa?'Sisa '+money(sisa):'✓ LUNAS'}</small></div><div><strong>${money(total)}</strong>${sisa?`<button type="button" class="wallet-small-pay" data-id="${x.id}">Bayar</button>`:''}</div></div>`}).join(''):'<div class="wallet-empty">Belum ada data.</div>';f.querySelectorAll('.wallet-small-pay').forEach(b=>b.onclick=()=>{kind==='debt'?payDebt(b.dataset.id):payBill(b.dataset.id);draw()})};f.querySelector('#specialAdd').onclick=()=>{close();kind==='debt'?openDebtForm():openBillForm()};draw()})}
function renderSummary(root,d){const masuk=d.tx.filter(x=>x.jenis==='masuk').reduce((a,x)=>a+Number(x.jumlah||0),0),keluar=d.tx.filter(x=>x.jenis==='keluar').reduce((a,x)=>a+Number(x.jumlah||0),0),saldo=masuk-keluar;const openDebt=d.debt.reduce((a,x)=>a+Math.max(0,Number(x.jumlah||0)-Number(x.terbayar||0)),0),openBill=d.bill.reduce((a,x)=>a+Math.max(0,Number(x.jumlah||0)-Number(x.terbayar||0)),0);root.innerHTML=`<section class="wallet-section"><h3>Ringkasan Wallet</h3><div class="wallet-summary-grid"><div><small>Saldo</small><b>${money(saldo)}</b></div><div><small>Hutang</small><b>${money(openDebt)}</b></div><div><small>Tagihan</small><b>${money(openBill)}</b></div></div><div class="wallet-actions"><button type="button" data-action="in">＋ Uang Masuk</button><button type="button" data-action="out">− Uang Keluar</button><button type="button" data-action="debt">🤝 Hutang</button><button type="button" data-action="bill">🧾 Tagihan</button></div></section>`;root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>openNav(b.dataset.action))}
function render(){const root=document.getElementById('walletApp');if(!root)return;const d=load(),masuk=d.tx.filter(x=>x.jenis==='masuk').reduce((a,x)=>a+Number(x.jumlah||0),0),keluar=d.tx.filter(x=>x.jenis==='keluar').reduce((a,x)=>a+Number(x.jumlah||0),0),saldo=masuk-keluar;root.innerHTML=`<div class="wallet-wrap"><div class="wallet-top"><div><div class="wallet-title">💰 Wallet</div><div class="wallet-sub">Keuangan pribadi & toko</div></div><button class="wallet-store-btn" id="walletStoreBtn">🛍️ Kembali ke Toko</button></div><div class="wallet-dashboard"><div class="wallet-balance"><span>Saldo</span><strong>${money(saldo)}</strong></div><div class="wallet-today wallet-summary-cards"><div class="wallet-today-card in"><small>Uang Masuk</small><strong>${money(masuk)}</strong></div><div class="wallet-today-card out"><small>Uang Keluar</small><strong>${money(keluar)}</strong></div></div><nav class="wallet-quick-nav wallet-main-nav"><button type="button" data-nav="summary">🏠<small>Ringkasan</small></button><button type="button" data-nav="in">💰<small>Uang Masuk</small></button><button type="button" data-nav="out">💸<small>Uang Keluar</small></button><button type="button" data-nav="debt">🤝<small>Hutang</small></button><button type="button" data-nav="bill">🧾<small>Tagihan</small></button><button type="button" data-nav="report">📊<small>Laporan</small></button></nav><div id="walletContent"></div></div></div>`;bind();renderSummary(document.getElementById('walletContent'),d)}
function renderTransactions(type){const root=document.getElementById('walletContent'),d=load(),rows=d.tx.filter(x=>x.jenis===type);if(!root)return;root.innerHTML=`<section class="wallet-section"><div class="wallet-section-head"><h3>${type==='masuk'?'💰 Uang Masuk':'💸 Uang Keluar'}</h3><button type="button" class="wallet-add-full" id="walletAddTx">＋ Tambah</button></div><div class="wallet-list">${rows.length?rows.slice().reverse().map(x=>`<div class="wallet-tx-row"><div><b>${esc(x.kategori)}</b><small>${new Date(x.tanggal).toLocaleString('id-ID')} · ${esc(x.keterangan||'')}</small></div><strong class="${type==='masuk'?'in':'out'}">${type==='masuk'?'+':'−'} ${money(x.jumlah)}</strong></div>`).join(''):'<div class="wallet-empty">Belum ada transaksi.</div>'}</div></section>`;root.querySelector('#walletAddTx').onclick=()=>openWalletForm(type)}
function renderWalletReport(){const d=load(),root=document.getElementById('walletContent');if(!root)return;const masuk=d.tx.filter(x=>x.jenis==='masuk').reduce((a,x)=>a+Number(x.jumlah||0),0),keluar=d.tx.filter(x=>x.jenis==='keluar').reduce((a,x)=>a+Number(x.jumlah||0),0),saldo=masuk-keluar;root.innerHTML=`<section class="wallet-section"><h3>📊 Laporan Wallet</h3><div class="wallet-report-grid"><div><span>Total uang masuk</span><b>${money(masuk)}</b></div><div><span>Total uang keluar</span><b>${money(keluar)}</b></div><div><span>Saldo</span><b>${money(saldo)}</b></div><div><span>Jumlah transaksi</span><b>${d.tx.length}</b></div></div><div class="wallet-report-list">${d.tx.slice().reverse().map(x=>`<div><span>${esc(x.kategori)} · ${new Date(x.tanggal).toLocaleDateString('id-ID')}</span><b>${x.jenis==='masuk'?'+':'−'} ${money(x.jumlah)}</b></div>`).join('')||'<div class="wallet-empty">Belum ada transaksi.</div>'}</div></section>`}
window.renderWalletReport=renderWalletReport;
function openNav(n){if(n==='summary'){renderSummary(document.getElementById('walletContent'),load());return}if(n==='in'||n==='out'){renderTransactions(n==='in'?'masuk':'keluar');return}if(n==='debt'){listSpecial('debt');return}if(n==='bill'){listSpecial('bill');return}if(n==='report'){renderWalletReport();return}}
function bind(){document.querySelectorAll('#walletApp .wallet-main-nav [data-nav]').forEach(b=>b.onclick=()=>openNav(b.dataset.nav));const s=document.getElementById('walletStoreBtn');if(s)s.onclick=()=>{document.getElementById('walletApp').classList.add('hidden');const st=document.getElementById('storeApp');if(st)st.classList.remove('hidden');window.scrollTo(0,0)}}
window.renderWallet=render;window.loadWallet=load;window.moneyWallet=money;window.walletToday=today;
storageTest();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(render,0));else setTimeout(render,0);
})();